name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: 
        npm install
        npm run build --if-present
        npm test
  
    - name: Uses Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn 
      
    - name: yarn install, build, and test
      run:
         yarn build        
        
    - name: deploy to surge
      run: surge ./build ahmadmustafeenprojectbootcamp03.surge.sh ${{secrets.SURGE_TOKEN}}
